app/admin/__init__.py
from flask import Blueprint, render_template, abort
from flask_login import login_required, current_user

from app.views.admin.UserView import UserView
from app.views.admin.course import CourseView
from app.views.admin.database import DatabaseView
from app.views.admin.database.CategoryView import DatabaseCategoryView
from app.views.admin.database.DatabaseImageView import DatabaseImageView
from app.views.admin.feature import FeatureView
from app.views.admin.monthly_plan import MonthlyPlanView
from app.views.admin.project import ProjectView
from app.views.admin.project.ProjectImageCategoryView import ProjectImageCategoryView
from app.views.admin.project.ProjectImageView import ProjectImageView
from app.views.admin.project.SubProjectView import SubProjectView
from app.views.admin.services import ServiceView

admin = Blueprint('admin', __name__, url_prefix='/admin')


@admin.before_request
@login_required
def is_admin():
    if not current_user.is_admin:
        abort(401)


ProjectView.register(admin, trailing_slash=False)
SubProjectView.register(admin, trailing_slash=False)
UserView.register(admin, trailing_slash=False)
DatabaseView.register(admin, trailing_slash=False)
DatabaseCategoryView.register(admin, trailing_slash=False)
DatabaseImageView.register(admin, trailing_slash=False)
ProjectImageCategoryView.register(admin, trailing_slash=False)
ProjectImageView.register(admin, trailing_slash=False)
FeatureView.register(admin, trailing_slash=False)
CourseView.register(admin, trailing_slash=False)
ServiceView.register(admin, trailing_slash=False)
MonthlyPlanView.register(admin, trailing_slash=False)


@admin.route('/', methods=('GET',))
@login_required
def dashboard():
    return render_template('admin/dashboard.html')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
import app.views.main

app/views/main.py
import shutil
from pathlib import Path
from uuid import uuid4

from flask import render_template, current_app, send_from_directory, abort, request, flash, redirect
from flask_login import login_required
from werkzeug.utils import secure_filename

from app.forms.front.main.ApplicationForms import ExcelToListForm
from app.functions.Convert_excel_to_list import file_to_network
from app.functions.Integrate_DEG import integrate_DEG_cluster_wise
from app.functions.integrate_excel_files import integrate_excel
from app.main import main
from app.views.helpers import allowed_file, save_file, zip_files


@main.route('/')
def homepage():
    return render_template('front/main/index.html')


@main.route('/applications', methods=('GET',))
@login_required
def applications():
    return render_template('front/main/applications.html')


@main.route('/inegrate_deg', methods=('POST', 'GET'))
def integrate_deg():
    if request.method == 'GET':
        return render_template('front/main/integrate_GED.html')
    req = request.form
    print(req)
    config = current_app.config

    if 'deg_files' not in request.files:
        flash('No file part')
        return redirect(request.url)
    files = request.files.getlist('deg_files')
    folder_name = str(uuid4())
    folder_path = Path.joinpath(config['UPLOAD_FOLDER'], folder_name)
    if files:
        # Create a directory to store the files

        if not Path.is_dir(folder_path): Path.mkdir(folder_path)

        for file in files:
            if file.filename == '':
                flash('No selected file', 'error')
                return redirect(request.url)

            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(Path.joinpath(folder_path, filename))
            else:
                flash(f"Please upload the correct excel file - {file.filename}")

    try:
        adj_p = float(req.get('adj_p'))
    except ValueError:
        adj_p = 0.05
    try:
        logFC_cutoff = float(req.get('logFC_cutoff'))
    except ValueError:
        logFC_cutoff = 0.2
    fill_zeros = req.get('fill_zeros') == '1'

    # file_name = integrate_DEG_cluster_wise(str(folder_path), adj_p=0.05, logFC_cutoff=0.2, fill_zeros=True)
    file_name = integrate_DEG_cluster_wise(str(folder_path), adj_p=adj_p, logFC_cutoff=logFC_cutoff,
                                           fill_zeros=fill_zeros)
    try:
        shutil.rmtree(folder_path)
        return send_from_directory(config['OUTPUT_PATH'], filename=file_name, as_attachment=True)
    except FileNotFoundError:
        abort(404)


@main.route('/integrate_excel_files', methods=('POST', 'GET'))
def integrate_excel_files():
    if request.method == 'GET':
        return render_template('front/main/integrate_excel.html')
    data = request.form.to_dict()

    if 'csv_file_1' not in request.files or 'csv_file_2' not in request.files:
        flash('Please modify_access all the files', 'error')
        return redirect(request.url)
    config = current_app.config

    # print(request.files.get('csv_file_1'))
    # print(data)
    # key_from_file2 = int(request.form.get('key_from_file_2'))
    # key_from_file1 = int(request.form.get('key_from_file_1'))
    # columns_of_interest_from_file1 = request.form.get('columns_of_interest_from_file1').split(',')
    # starting_column_file2 = int(request.form.get('starting_column_file_2'))

    try:
        saved_file_1_path = save_file(request.files.get('csv_file_1'))
        saved_file_2_path = save_file(request.files.get('csv_file_2'))
    except Exception:
        flash(' Make sure to modify_access the correct files', 'error')
        return redirect(request.url)
    try:
        columns_of_interest_from_file1 = list(int(x) for x in data.get('columns_of_interest_from_file1').split(','))
    except:
        flash('Column of interest is invalid. Please separate the columns by a comma(,)', 'error')
        return redirect(request.url)
    try:
        starting_column_file2 = int(data.get('starting_column_file_2'))
    except:
        flash('Starting column from file 2 must be an integer', 'error')
        return redirect(request.url)
    try:
        key_from_file1 = int(data.get('key_column_from_file_1'))
    except:
        flash('Key column from file 1 is invalid. make sure it is a number', 'error')
        return redirect(request.url)
    try:
        key_from_file2 = int(data.get('key_column_from_file_2'))
    except:
        flash('Key column from file 2 is invalid. make sure it is a number', 'error')
        return redirect(request.url)

    file_name = integrate_excel(saved_file_1_path, saved_file_2_path,
                                columns_of_interest_from_file1=columns_of_interest_from_file1,
                                key_from_file1=key_from_file1, key_to_file2=key_from_file2,
                                starting_column_file2=starting_column_file2, new_column_name='Test',
                                add_annotation="Gene location",
                                add_report=True)
    if not file_name:
        flash('An error occurred while integrating the files. Please check the input and try again', 'error')
        return redirect(request.url)
    files = [str(Path.joinpath(config['OUTPUT_PATH'], file_name + '.xlsx'))]

    report_name = str(Path.joinpath(config['OUTPUT_PATH'], 'reports', file_name + '.txt'))
    files.append(report_name)

    zipped_filename = zip_files(files)
    try:
        return send_from_directory(config['OUTPUT_PATH'], filename=zipped_filename, as_attachment=True)
    except FileNotFoundError:
        abort(404)


@main.route('/excel_to_list', methods=('POST', 'GET'))
def excel_to_list():
    form = ExcelToListForm()
    if form.validate_on_submit():
        if 'file' not in request.files:
            flash('Excel file not uploaded', 'error')
            return redirect(request.url)
        config = current_app.config

        try:
            excel_file = save_file(request.files.get('file'))
        except Exception:
            flash('Make sure to modify_access the correct files', 'error')
            return redirect(request.url)
        file_name = file_to_network(excel_file, form.key_column.data, form.target_column.data, form.delimiter.data)
        if not file_name:
            flash('An error occurred while integrating the files. Please check the input and try again', 'error')
            return redirect(request.url)
        # file_path = str(Path.joinpath(config['OUTPUT_PATH'], file_name + '.xlsx'))
        try:
            return send_from_directory(config['OUTPUT_PATH'], filename=file_name, as_attachment=True)
        except FileNotFoundError:
            abort(404)

    return render_template('front/main/excel_to_list.html',form=form)

app/templates/layout/front/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <meta http-equiv="Content-Security-Policy" content="">
    <title> CytoTalk, LLC
    </title>
    <!--    Bootstrap-->

    {#    <link href="{{ url_for('static', filename='main/image/logos/logo_condensed.png') }} " rel="icon" type="image/x-icon"/>#}

    <link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='main/image/favicon') }}/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='main/image/favicon') }}/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='main/image/favicon') }}/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='main/image/favicon') }}/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='main/image/favicon') }}/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='main/image/favicon') }}/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='main/image/favicon') }}/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='main/image/favicon') }}/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='main/image/favicon') }}/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="{{ url_for('static', filename='main/image/favicon') }}/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='main/image/favicon') }}/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='main/image/favicon') }}/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='main/image/favicon') }}/favicon-16x16.png">
    <link rel="manifest" href="{{ url_for('static', filename='main/image/favicon') }}/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <!-- Font Awesome icons (free version)-->
    <script crossorigin="anonymous" src="https://use.fontawesome.com/releases/v5.15.1/js/all.js"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{{ url_for('static', filename='main/css/custom.css') }}" rel="stylesheet"/>
    <link href="{{ url_for('static', filename='vendor/material-design/css/mdb.min.css') }} " rel="stylesheet"/>
    {#    <link href="{{ url_for('static', filename='main/css/styles.css') }}" rel="stylesheet"/>#}
    {% block css %}{% endblock %}
</head>

<body id="page-top">
<!-- Navigation-->

<nav id="mainNav" class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.homepage') }}">
            <img
                    style="max-height: 30px;width: auto"
                    loading="lazy"

                    alt="Cytotalk Logo"
                    src="{{ url_for('static',filename='main/image/logos/logo_main.png') }}"/>
        </a>

        <!-- Toggle button -->
        <button
                class="navbar-toggler"
                type="button"
                data-mdb-toggle="collapse"
                data-mdb-target="#navbarButtonMenu"
                aria-controls="navbarButtonMenu"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarButtonMenu">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ request.host_url }}">Home</a>
                </li>
                <li class="nav-item">

                    <a class="nav-link"
                       href="https://www.applicagen.com/groups/5fe7dbfe3dd1636795b0f2d7"> Our Activities!
                    </a>
                </li>
                <li class="nav-item">

                    <a class="nav-link" href="{{ url_for('main.applications') }}"
                    >Applications
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="{{ url_for('database.DatabaseView:index') }}"
                    >Databases</a>
                </li>
                    <a class="nav-link" href="{{ url_for('project.ProjectView:index') }}">Projects</a>
                </li>
                {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-right" href="{{ url_for('auth.LoginView:index') }}">Login</a>
                    </li>

                    {#<li class="nav-item">
                        <a class="nav-link text-right" href="{{ url_for('auth.RegistrationView:index') }}">Register</a>
                    </li>#}
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-right" href="{{ url_for('auth.LoginView:logout') }}">Logout</a>
                    </li>

                {% endif %}

                {% if current_user.is_authenticated and current_user.is_admin%}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.dashboard') }}">Dashboard</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div>
    {% with messages = get_flashed_messages(category_filter=["error"]) %}
        {% if messages %}
            <div class=flashes>
                {% for message in messages %}
                    <div class="alert alert-danger alert-dismissible">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    {% with messages = get_flashed_messages(category_filter=["success"]) %}
        {% if messages %}
            <div class=flashes>
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    {% with messages = get_flashed_messages(category_filter=["warning"]) %}
        {% if messages %}
            <div class=flashes>
                {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
</div>
<div class="content">

    {% block content %}
    {% endblock %}
</div>
<!-- Footer-->
<footer class="footer p-4">
    <div class="d-flex align-items-end">
        <div class="col-sm-3">
            <p class="text-white">
                1603 Capitol Ave. Suite 310 A105, Cheyenne, Wyoming 82001, United States
            </p>
            <p class="text-white">
                Email: info@cytotalk.com
            </p>
        </div>
        <div class="col-sm-6 text-white text-center">
                    <p>Copyright © 2021 CytoTalk - All Rights Reserved.</p>

        </div>
        <div class="col-sm-3">

            <div class="d-flex flex-wrap">

            <div class="p-2">


            <a class="btn btn-light btn-social mx-2" href="https://www.facebook.com/cytotalk/"><i
                    class="fab fa-facebook-f"></i></a>
            </div>
            <div class="p-2">

            <a class="btn btn-light btn-social mx-2" href="https://www.instagram.com/Cytotalk2020/"><i
                    class="fab fa-instagram"></i> </a>
            </div>
            </div>

        </div>

    </div>
    <div>
    </div>
</footer>

<!-- Bootstrap core JS-->
<script  src="{{ url_for('static', filename='vendor/jquery-3.6/jquery.js') }} "></script>
<script  src="{{ url_for('static', filename='vendor/material-design/js/mdb.min.js') }} "></script>
<!-- Third party plugin JS-->
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>#}
<!-- Contact form JS-->
<!-- Core theme JS-->
<script src="{{ url_for('static', filename='main/js/scripts.js') }}"></script>
{% block scripts %}{% endblock %}
</body>

</html>