app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
import app.views.main

app/views/main.py
import shutil
from pathlib import Path
from uuid import uuid4

from flask import render_template, current_app, send_from_directory, abort, request, flash, redirect
from flask_login import login_required
from werkzeug.utils import secure_filename

from app.forms.front.main.ApplicationForms import ExcelToListForm
from app.functions.Convert_excel_to_list import file_to_network
from app.functions.Integrate_DEG import integrate_DEG_cluster_wise
from app.functions.integrate_excel_files import integrate_excel
from app.main import main
from app.views.helpers import allowed_file, save_file, zip_files


@main.route('/')
def homepage():
    return render_template('front/main/index.html')


@main.route('/applications', methods=('GET',))
@login_required
def applications():
    return render_template('front/main/applications.html')


@main.route('/inegrate_deg', methods=('POST', 'GET'))
def integrate_deg():
    if request.method == 'GET':
        return render_template('front/main/integrate_GED.html')
    req = request.form
    print(req)
    config = current_app.config

    if 'deg_files' not in request.files:
        flash('No file part')
        return redirect(request.url)
    files = request.files.getlist('deg_files')
    folder_name = str(uuid4())
    folder_path = Path.joinpath(config['UPLOAD_FOLDER'], folder_name)
    if files:
        # Create a directory to store the files

        if not Path.is_dir(folder_path): Path.mkdir(folder_path)

        for file in files:
            if file.filename == '':
                flash('No selected file', 'error')
                return redirect(request.url)

            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(Path.joinpath(folder_path, filename))
            else:
                flash(f"Please upload the correct excel file - {file.filename}")

    try:
        adj_p = float(req.get('adj_p'))
    except ValueError:
        adj_p = 0.05
    try:
        logFC_cutoff = float(req.get('logFC_cutoff'))
    except ValueError:
        logFC_cutoff = 0.2
    fill_zeros = req.get('fill_zeros') == '1'

    # file_name = integrate_DEG_cluster_wise(str(folder_path), adj_p=0.05, logFC_cutoff=0.2, fill_zeros=True)
    file_name = integrate_DEG_cluster_wise(str(folder_path), adj_p=adj_p, logFC_cutoff=logFC_cutoff,
                                           fill_zeros=fill_zeros)
    try:
        shutil.rmtree(folder_path)
        return send_from_directory(config['OUTPUT_PATH'], filename=file_name, as_attachment=True)
    except FileNotFoundError:
        abort(404)


@main.route('/integrate_excel_files', methods=('POST', 'GET'))
def integrate_excel_files():
    if request.method == 'GET':
        return render_template('front/main/integrate_excel.html')
    data = request.form.to_dict()

    if 'csv_file_1' not in request.files or 'csv_file_2' not in request.files:
        flash('Please modify_access all the files', 'error')
        return redirect(request.url)
    config = current_app.config

    # print(request.files.get('csv_file_1'))
    # print(data)
    # key_from_file2 = int(request.form.get('key_from_file_2'))
    # key_from_file1 = int(request.form.get('key_from_file_1'))
    # columns_of_interest_from_file1 = request.form.get('columns_of_interest_from_file1').split(',')
    # starting_column_file2 = int(request.form.get('starting_column_file_2'))

    try:
        saved_file_1_path = save_file(request.files.get('csv_file_1'))
        saved_file_2_path = save_file(request.files.get('csv_file_2'))
    except Exception:
        flash(' Make sure to modify_access the correct files', 'error')
        return redirect(request.url)
    try:
        columns_of_interest_from_file1 = list(int(x) for x in data.get('columns_of_interest_from_file1').split(','))
    except:
        flash('Column of interest is invalid. Please separate the columns by a comma(,)', 'error')
        return redirect(request.url)
    try:
        starting_column_file2 = int(data.get('starting_column_file_2'))
    except:
        flash('Starting column from file 2 must be an integer', 'error')
        return redirect(request.url)
    try:
        key_from_file1 = int(data.get('key_column_from_file_1'))
    except:
        flash('Key column from file 1 is invalid. make sure it is a number', 'error')
        return redirect(request.url)
    try:
        key_from_file2 = int(data.get('key_column_from_file_2'))
    except:
        flash('Key column from file 2 is invalid. make sure it is a number', 'error')
        return redirect(request.url)

    file_name = integrate_excel(saved_file_1_path, saved_file_2_path,
                                columns_of_interest_from_file1=columns_of_interest_from_file1,
                                key_from_file1=key_from_file1, key_to_file2=key_from_file2,
                                starting_column_file2=starting_column_file2, new_column_name='Test',
                                add_annotation="Gene location",
                                add_report=True)
    if not file_name:
        flash('An error occurred while integrating the files. Please check the input and try again', 'error')
        return redirect(request.url)
    files = [str(Path.joinpath(config['OUTPUT_PATH'], file_name + '.xlsx'))]

    report_name = str(Path.joinpath(config['OUTPUT_PATH'], 'reports', file_name + '.txt'))
    files.append(report_name)

    zipped_filename = zip_files(files)
    try:
        return send_from_directory(config['OUTPUT_PATH'], filename=zipped_filename, as_attachment=True)
    except FileNotFoundError:
        abort(404)


@main.route('/excel_to_list', methods=('POST', 'GET'))
def excel_to_list():
    form = ExcelToListForm()
    if form.validate_on_submit():
        if 'file' not in request.files:
            flash('Excel file not uploaded', 'error')
            return redirect(request.url)
        config = current_app.config

        try:
            excel_file = save_file(request.files.get('file'))
        except Exception:
            flash('Make sure to modify_access the correct files', 'error')
            return redirect(request.url)
        file_name = file_to_network(excel_file, form.key_column.data, form.target_column.data, form.delimiter.data)
        if not file_name:
            flash('An error occurred while integrating the files. Please check the input and try again', 'error')
            return redirect(request.url)
        # file_path = str(Path.joinpath(config['OUTPUT_PATH'], file_name + '.xlsx'))
        try:
            return send_from_directory(config['OUTPUT_PATH'], filename=file_name, as_attachment=True)
        except FileNotFoundError:
            abort(404)

    return render_template('front/main/excel_to_list.html',form=form)

app/templates/front/main/applications.html
{% extends 'layout/front/main.html' %}
{% block content %}
<div class="container">
    <h1 class="text-primary text-center">Our Applications</h1>

    <div class="text-center">
        <a href="{{ url_for('main.integrate_deg') }}" class="m-5 btn btn-light btn-md  js-scroll-trigger">Integrated DEG</a>
        <a href="{{ url_for('main.integrate_excel_files') }}" class="m-5 btn btn-light btn-md  js-scroll-trigger">Integrated Excel files</a>
        <a href="{{ url_for('main.excel_to_list') }}" class="m-5 btn btn-light btn-md  js-scroll-trigger">Excel to list</a>
    </div>
    </div>
{% endblock %}

app/templates/front/main/excel_to_list.html
{% extends 'layout/front/main.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 m-auto">
                <h1 class="text-dark">
                    Convert Excel to list
                </h1>
                <form enctype="multipart/form-data" method="post" action="{{ url_for('main.excel_to_list') }}">

                    {{ wtf.quick_form(form) }}
                    {#<input id="csrf_token" name="csrf_token" type="hidden" value="{{ csrf_token() }}">

                        <div class="col-sm-6 m-auto">
                            <div class="form-group">
                                <label for="file">Excel File</label>
                                <input class="form-control" type="file" name="file" id="file">
                            </div>
                            <div class="form-group">
                                <label for="key_column">Key Column</label>
                                <input class="form-control" type="text" name="key_column"
                                       id="key_column">
                            </div>
                            <div class="form-group">
                                <label for="target_column">Target Column</label>
                                <input class="form-control" type="text" name="target_column"
                                       id="target_column">
                            </div>
                            <div class="form-group">
                                <label for="delimiter">Delimiter</label>
                                <input class="form-control" type="text" name="delimiter"
                                       id="delimiter" placeholder="', ">
                            </div>
                        </div>
                    <div class="p-3 text-center">
                        <button class="btn btn-success btn-lg" type="submit">Submit</button>
                    </div>#}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/front/main/index.html
{% extends 'layout/front/main.html' %}
<!-- Masthead-->
{% block content %}
    <header style="background-image: url('{{ url_for('static',filename='main/image/header-bg.jpg') }}')" class="masthead">
        <div class="container p-5">
            <h1 class="text-center text-white">
                Welcome to <br> CytoTalk, LLC
            </h1>
            <div class="row flex-column justify-content-center align-items-center">
                <div class="col-sm-3">
                    <a class="btn m-2 btn-light btn-block btn-md  js-scroll-trigger"
                       href="https://www.applicagen.com/groups/5fe7dbfe3dd1636795b0f2d7" style="font-size: 30px;"> Our Activities!
                    </a>
                </div>
                <div class="col-sm-3">
                    <a class="m-2 btn btn-light btn-block btn-md  js-scroll-trigger" href="{{ url_for('main.applications') }}"
                       style="font-size: 30px;">Applications
                    </a>
                </div>
                <div class="col-sm-3">
                    <a class="m-2 btn btn-light btn-block btn-md  js-scroll-trigger"
                       href="{{ url_for('database.DatabaseView:index') }}"
                       style="font-size: 30px;">Databases
                    </a>
                </div>
                <div class="col-sm-3">
                    <a class="m-2 btn btn-light btn-block btn-md  js-scroll-trigger"
                       href="{{ url_for('course.CourseView:index') }}"
                       style="font-size: 30px;">Courses
                    </a>
                </div>
                <div class="col-sm-3">
                    <a class="m-2 btn btn-light btn-block btn-md  js-scroll-trigger"
                       href="{{ url_for('services.ServiceView:index') }}"
                       style="font-size: 30px;">Our services
                    </a>
                </div>
                <div class="col-sm-3">
                    <a class="m-2 btn btn-light btn-block btn-md  js-scroll-trigger"
                       href="{{ url_for('monthly_plans.MonthlyPlanView:index') }}"
                       style="font-size: 30px;">Monthly plans
                    </a>
                </div>
                <div class="col-sm-3">
                    <a class="m-2 btn btn-light btn-block btn-md  js-scroll-trigger"
                       href="{{ url_for('project.ProjectView:index') }}"
                       style="font-size: 30px;">Projects
                    </a>
                </div>
            </div>

        </div>
    </header>
{% endblock %}

app/templates/front/main/integrate_GED.html
{% extends 'layout/front/main.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 m-auto">
                <h1 class="text-dark text-center">
                    Integrate DEB
                </h1>
                <form action="{{ url_for('main.integrate_deg') }}" enctype="multipart/form-data" method="post">
                    <input id="csrf_token" name="csrf_token" type="hidden" value="{{ csrf_token() }}">

                    <div class="form-group">
                        <label for="integrate_deg_files">Files</label>
                        <input accept=".xlsx,.xls" class="form-control" id="integrate_deg_files" multiple name="deg_files"
                               required type="file">

                    </div>
                    <div class="form-group">
                        <label for="adj_p">adj_p</label>
                        <input class="form-control" id="adj_p" name="adj_p" required type="text">

                    </div>
                    <div class="form-group">
                        <label for="logFC_cutoff">logFC_cutoff</label>
                        <input class="form-control" id="logFC_cutoff" name="logFC_cutoff" required type="text">

                    </div>
                    <div class="form-group">
                        <label for="fill_zeros">fill_zeros</label>
                        <select class="form-control" id="fill_zeros" name="fill_zeros" required>
                            <option value="0">No</option>
                            <option value="1">Yes</option>
                        </select>

                    </div>
                    <div class="form-group">
                        <button class="btn btn-success btn-md" type="submit"> Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/front/main/integrate_excel.html
{% extends 'layout/front/main.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 m-auto">
                <h1 class="text-dark text-center">
                    Integrate Excel files
                </h1>              
                
                <p class="text-dark text-center">This function takes 2 excel (*.xlsx) files to integrate values from file 1 to file 2.<br /><br />
                File 1: The file which contains columns to be merged to the other file (file 2).<br />
                File 1 key: The column in file 1 that includes key values to be matched with file 2.<br />
                Columns of interest: The columns in file 1 which you want to merge to file 2. It should be comma separated as this 2,3,5<br /><br />
                File 2: The file that you want to paste new information to.<br />
                File 2 key: The column in file 2 that includes key values to be matched with file 1.<br />
                Starting column: The column number in file 2 that the new information will be pasted starting from it.<br />
                Note: Currently, the function is case sensetive. "hi" is not equal to "HI" while matching keys from both files.<br />
                </p>
                <form enctype="multipart/form-data" method="post" action="{{ url_for('main.integrate_excel_files') }}">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="csv_file_1">File 1</label>
                                <input class="form-control" type="file" name="csv_file_1" id="csv_file_1">
                            </div>
                            <div class="form-group">
                                <label for="key_column_from_file_1">File 1 Key</label>
                                <input class="form-control" type="number" name="key_column_from_file_1" id="key_column_from_file_1">
                            </div>

                            <div class="form-group">
                                <label for="columns_of_interest_from_file1">Columns of interest <span class="text-sm">(Separate by commas)</span></label>
                                <input class="form-control" type="text" name="columns_of_interest_from_file1"
                                       id="columns_of_interest_from_file1" placeholder="2,5">
                            </div>
                        </div>
                        <div class="col-sm-6 border-left">
                            <div class="form-group">
                                <label for="csv_file_2">File 2</label>
                                <input class="form-control" type="file" name="csv_file_2" id="csv_file_2">
                            </div>
                             <div class="form-group">
                                <label for="key_column_from_file_2">File 2 Key</label>
                                <input class="form-control" type="number" name="key_column_from_file_2" id="key_column_from_file_2">
                            </div>
                            {#<div class="form-group">
                                <label for="columns_of_interest_from_file_2">Columns of interest from file 2 <span class="text-sm">(Separate by commas)</span></label>
                                <input class="form-control" type="text" name="columns_of_interest_from_file_2"
                                       id="columns_of_interest_from_file_2" placeholder="2,5">
                            </div>#}
                            <div class="form-group">
                                <label for="starting_column_file_2">Starting column</label>
                                <input class="form-control" type="number" name="starting_column_file_2"
                                       id="starting_column_file_2">
                            </div>
                        </div>
                    </div>
                                    <div class="p-3 text-center">
                    <button class="btn btn-success btn-lg" type="submit">Submit</button>
                                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}